### PR TITLE
Fixed the issue #30 - Large integer overflows

### PR DESCRIPTION
**Pull request by CognitiveDisson**
Fixed the issue #30

### CODE REVIEW

**Comment by koke** [comment]
Interesting issue. I'm OK with extending `parseInteger` beyond what the standard specifies and use `long long`. But anything higher than that is problematic.

I see that when `longLongValue` returns `LLONG_MAX`, indicating that it overflows, you then try a number formatter. `NSNumberFormatter` can indeed process larger numbers, but when you go above `LLONG_MAX`, it starts storing them as `double` and you lose precision.

So this might not work at all as you expect: if you add 1, 10, or 100, to the number in `OverflowInteger64TestCase.xml`, the test at `testOverflowIntegerTestCase` still passes. The debugger will tell you why:

screen shot 2016-02-03 at 18 45 05

The `parsedResult` is a `double`, but it seems to round down to the same value than the expected result, so it's treated as the same number.

I don't think we can handle anything above `LLONG_MAX` without resorting to bignum libraries, and that's not happening for something outside the spec.

**Comment by aerych** [comment]
Looks good and tests pass. :shipit:

**Comment by koke** [comment]
@aerych was your comment maybe for #32? :wink:

**Comment by aerych** [comment]
> was your comment maybe for #32? :wink:

Bah!  Yes it was, sorry. :)

**Pull request merged**
