### PR TITLE
Update tests and project to use XCTests.

### PR DESCRIPTION
**Pull request by SergioEstevao**

### CODE REVIEW

**Comment by koke** [comment]
Moving the conversation here from slack, a few concerns:
- The migration to XCTest was already done in #27. It wasn't merged to develop but you already took care of that.
- After the merge, this PR adds back a bunch of `.h` files that aren't needed.
- The only remaining thing on this PR then is bumping the deployment version to iOS 8 / OS X 10.10. I believe this is just to be able to use the new Base64 methods. In that case, those are available in iOS 7 / OS X 10.9, so that would be the new minimum requirement.

**Comment by SergioEstevao** [comment]
@koke thanks for the feedback.

I tried to upgrade the code for use the iOS 7 base 64 encoding methods. The only issue I found is that these methods don't support the direct encoding of NSInputStream and NSFileHandle so I was thinking to implement some categories to the classes to do the encoding using the iOS 7 methods. What do you think?

**Comment by koke** [comment]
Honestly, I think I'd leave things as they are. The methods in `WPBase64Utils` would take care of the NSInputStream and NSFileHandle stuff, but I worry that some slight difference in how the implementations work might create subtle bugs.

**Comment by koke** [comment]
:shipit:

**Pull request merged**
