### PR TITLE
Remove CircleCI

### PR DESCRIPTION
**Pull request by jkmassel**
Adds a build status badge, and ensures that CircleCI is fully removed from the repo

### CODE REVIEW

**Comment by AliSoftware** [comment]
In https://github.com/Automattic/simplenote-android/pull/1455#discussion_r693622633 we agreed with @mokagio that those badges are probably not worth it because the CI status is displayed by the modern GitHub UI nowadays… so not sure it's worth adding this one here?

image

**Comment by mokagio** [comment]
Here, too:

image

I like the "simplicity" of not having it, but 🤷‍♂️ If the community still expects a badge as a sign of a project well kept, happy to add it. This is an easy decision to revert, so if you feel its ought to land, feel free to admin-merge.

**Comment by oguzkocer** [comment]
> If the community still expects a badge as a sign of a project well kept, happy to add it

Simplenote-Android was showing a green badge if I remember correctly even though the CI hasn't run a job in the last year or so. I think the commit status is a bit more valuable in that regard because it also has a timestamp 🤷

**Comment by mokagio** [comment]
> Here, too:
>
> image

@AliSoftware mad me realized that is actually feature added by the [Refined GitHub Chrome Extension](https://github.com/sindresorhus/refined-github) that I use.

I don't think that changes the rationale for removing the badge, but thought worth pointing it out 😄

**Comment by jkmassel** [comment]
Welp this PR is quite useless now 😜

Thanks for the thoughts, y'all – closing!

**Pull request closed without merging**
